version: '3.7'

services:
  apiserver:
    image: aimi614/wxapiserver:v3.9.5.81
    container_name: apiserver-v3.9.5.81
    restart: unless-stopped
    tty: true
    ports:
      - "19088:19088"
      - "8080:8080"
      - "5900:5900"
    environment:
      - WINEDEBUG=fixme-all
      - TZ=Asia/Shanghai
      - GIN_MODE=release
      - TEMP_DIR=/home/app/.wine/drive_c/data
#      - MSG_QUEUE_ADDR=redis:6379 # redis 消息队列地址
      - MSG_LISTENER_PORT=19099
      - VIRTUAL_MACHINE_URL=http://localhost:19088
#      - REDIS_ADDR=redis:6379
    volumes:
      - ./data/data:/home/app/.wine/drive_c/data
      - ./data/wechat:/home/app/.wine/drive_c/users/app/Documents/WeChat Files
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:19088/api/checkLogin" ]
      interval: 30s
      timeout: 20s # 一般是20s旁边完成注入
      retries: 3

#  redis:
#    image: redis:alpine
#    restart: unless-stopped
#    volumes:
#      - ./data/redis:/data